### ISSUE TITLE
Clarification Documentation Question

### ISSUE THREAD

**Issue by mosesrenegade** [doorkeeper-gem/doorkeeper-sinatra-client#39]
As I'm walking through your application I"m wondering what exactly goes into the .env environment for the OAUTH sections.

It says:
```
    PUBLIC_CLIENT_ID                 = "129477f..."
    PUBLIC_CLIENT_REDIRECT_URI       = "c1eec90..."

    CONFIDENTIAL_CLIENT_ID           = "129477f..."
    CONFIDENTIAL_CLIENT_SECRET       = "c1eec90..."
    CONFIDENTIAL_CLIENT_REDIRECT_URI = "http://localhost:9393/callback"

    PROVIDER_URL = "http://you-server-app.com"
```
However whats not clear is where the PUBLIC_CLIENT_ID/PUBLIC_CLIENT_REDIRECT_URI all comes from. Is there a way I can figure this out using the doorgem-provider app how I can fill these values in?

Is it by adding an Authorized Application? If which values go where?

**Comment by felipeelias** [comment]
Hi,

You'll need to create apps manually in doorkeeper provider app and it's up to you to decide which one is which.

By default, the provider app creates [this one as an example](https://github.com/doorkeeper-gem/doorkeeper-provider-app/blob/master/db/seeds.rb)
